# Generated by Django 3.1.1 on 2020-11-09 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Batches',
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='TeacherProgre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(blank=True, max_length=127, null=True)),
                ('partialcomplete', models.BooleanField(default=False)),
                ('fullcomplete', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.batches')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.fileupload')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TeacherProgres',
                'verbose_name_plural': 'TeacherProgres',
            },
        ),
        migrations.CreateModel(
            name='StudentProgres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videolen', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, max_length=127, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.fileupload')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StudentProgres',
                'verbose_name_plural': 'StudentProgres',
            },
        ),
    ]
