# Generated by Django 3.1.1 on 2020-11-09 11:08
''' '''
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True
    
    dependencies = [
    ]


    #Creates model in the history and correspounding database matching with it
    operations = [


        #Creation of Multiple question database matching with the Mcquestion model
        migrations.CreateModel(
            name='Mcquestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('text1', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('text3', models.CharField(max_length=255)),
                ('is_correct', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Mcquestions',
                'verbose_name_plural': 'Mcquestions',
            },
        ),


        #Creates the database matching with the Number of question model
        migrations.CreateModel(
            name='NumberOfQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplechoice', models.CharField(max_length=255, verbose_name='number of questions show in mcquestions')),
                ('mock', models.CharField(max_length=255, verbose_name='number of questions show in mock')),
                ('assement', models.CharField(max_length=255, verbose_name='number of questions show in assement')),
            ],
            options={
                'verbose_name': 'NumberOfQuestions',
                'verbose_name_plural': 'NumberOfQuestions',
            },
        ),


        #Creates the database matching with the Student model
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='studentimages')),
                ('otp', models.CharField(blank=True, max_length=17, null=True)),
                ('otp_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('varifed', models.BooleanField(default=False)),
            ],
        ),


        #Creates database matching with the model Student Progress
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Studentanswers', to='mcquestions.mcquestions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentProgress', to='mcquestions.student')),
            ],
            options={
                'verbose_name': 'StudentProgres',
                'verbose_name_plural': 'StudentProgres',
            },
        ),


        #Creates database matching with the model Student Progress
        migrations.CreateModel(
            name='StudentPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('percentage', models.CharField(max_length=255, verbose_name='percentage')),
                ('percentag', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupancode', models.CharField(max_length=255, verbose_name='coupan code')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentPercentage', to='mcquestions.student')),
            ],
        ),
    ]
