# Generated by Django 3.1.1 on 2020-11-09 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(blank=True, max_length=127, null=True)),
                ('priceusd', models.CharField(blank=True, max_length=127, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=127, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=127, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('image', models.FileField(upload_to='courseimage')),
                ('price', models.CharField(blank=True, max_length=127, null=True)),
                ('priceusd', models.CharField(blank=True, max_length=127, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='image')),
                ('uploadfile', models.FileField(upload_to='video')),
                ('url', models.CharField(blank=True, max_length=127, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.chapter')),
                ('courses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('text1', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('text3', models.CharField(max_length=255)),
                ('is_correct', models.CharField(max_length=255)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'MockTest',
                'verbose_name_plural': 'MockTest',
            },
        ),
        migrations.CreateModel(
            name='NumberofMock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'NumberofMock',
                'verbose_name_plural': 'NumberofMock',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('media', models.ManyToManyField(related_name='multipleVideo', to='course.FileUpload')),
                ('purchaseuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MockTestProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(default=False)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MockTestsCourse', to='course.course')),
                ('mock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.numberofmock')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MockTestanswers', to='course.mocktest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MockTestsProgress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MockTestProgres',
                'verbose_name_plural': 'MockTestProgres',
            },
        ),
        migrations.CreateModel(
            name='MockTestPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentag', models.CharField(max_length=255, verbose_name='mockpercentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MockTest', to='course.course')),
                ('mock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.numberofmock')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MockTestsPercentage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MockTestPercentage',
                'verbose_name_plural': 'MockTestPercentage',
            },
        ),
        migrations.AddField(
            model_name='mocktest',
            name='mock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.numberofmock'),
        ),
        migrations.CreateModel(
            name='CurrentVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=127, null=True)),
                ('coures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('currenv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.fileupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch', models.IntegerField(default=0)),
                ('vtime', models.CharField(blank=True, max_length=50, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('mediafile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.fileupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='course.course'),
        ),
        migrations.CreateModel(
            name='AssignmentsTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('text1', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('text3', models.CharField(max_length=255)),
                ('is_correct', models.CharField(max_length=255)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Assegment',
                'verbose_name_plural': 'Assegment',
            },
        ),
        migrations.CreateModel(
            name='AssignmentsProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assignmentcourse', to='course.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assignmentsanswers', to='course.assignmentstest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssignmentProgress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AssegmentProgres',
                'verbose_name_plural': 'AssegmentProgres',
            },
        ),
        migrations.CreateModel(
            name='AssignmentsPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentag', models.CharField(max_length=255, verbose_name='Assignmentpercentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assignmentchapter', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssignmentPercentage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AssegmentPercentage',
                'verbose_name_plural': 'AssegmentPercentage',
            },
        ),
        migrations.CreateModel(
            name='assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.FileField(upload_to='assigment')),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
